### ISSUE TITLE
overlay not transparent [solved]

### ISSUE THREAD

**Issue by luca-ing** [jahnf/Projecteur#10]
**Observation:**
When I use Projecteur's lens function (click the lens button on the presenter), I get a completely dark grey screen with a black circle, which moves as I move the presenter (obviously the lens).
The colour difference is minimal.

**Expectation:**
When I use the lens function, I get a normally-visible circle, while the area outside the circle is "shaded" (darkened but still clearly visible).

**Steps to reproduce:**
* Start Projecteur 0.4-alpha.9
* try to use the lens feature
* always reproducible

**Environment:**
* compiled using qt 5.12.2
* using i3 window manager
* environment:
```bash
$ uname -a
Linux dell 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ i3 --version
i3 version 4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors

```

**Comment by jahnf** [comment]
While I do not use or have ever used i3 - I did a quick test in a virtual machine with Manjaro Linux i3 Edition - where it seems to work - see screenshot: 
@luca-ing Could you please recheck if the issue at your setup is still present with the latest version from develop?
![i3-virtualbox-test-manjaro-linux](https://user-images.githubusercontent.com/5852240/57777902-3b105e80-7723-11e9-9e87-137017add4cc.png)

**Comment by luca-ing** [comment]
I confirm the issue is still present for me in tody's develop.

I verified it's not coupled to i3 -- in Gnome and LXDE I ovserve the same behaviour.

It's presumably something to do with my environment -- but I'm at a loss where to start looking.

**Comment by jahnf** [comment]
One thing I can think of: Could it be a graphics driver issue? Is graphics hardware acceleration supported? QtQuick, which is used for the overlay window usually uses OpenGL.

**Comment by jbrea** [comment]
Same problem here. Did you find a solution?
I am on arch linux with i3wm. Graphics hardware acceleration should be supported (at least I get a reasonable output from `vainfo`).

**Comment by rj-jesus** [comment]
If I'm not mistaken you need to be running a compositing manager.

Please try again after running for instance `xcompmgr -c -t-6 -l-6 -o.1`.

**Comment by jbrea** [comment]
That's it. Thanks a lot @rj-jesus!

**Comment by luca-ing** [comment]
I confirm using xcompmgr (which wasn't even installed) solved the problem for me.
Thanks a lot, @rj-jesus !

**Comment by jahnf** [comment]
Updated README (2cf43106d58bfa8c59a6e4705a877cdb119ce435) - also on X11 platforms a warning in the preferences dialog is shown if no compositing manager is running.
