### ISSUE TITLE
Feature Request: projecteur -c spot=toggle command

### ISSUE THREAD

**Issue by flortsch** [jahnf/Projecteur#104]
Hello @jahnf,

first of all, I want to thank you a lot for your work and your great tool. I was looking for a spotlight tool that I could use in my programming classes, and projecteur works great with its shell commands bound to keyboard shortcuts. I played around with the command line, but I could not find a way to toggle the spotlight, i.e., switch between the `on` and `off` state with a single command. Of course, one could wrap the existing commands in a custom script and store the current state, but it would be easier if the tool already provides such a command. So I suggest adding a command like `projecteur -c spot=toggle` that would allow binding the spotlight to a single keyboard shortcut.

Best regards
Florian

**Comment by jahnf** [comment]
@flortsch  I still need to verify the changes didn't affect any behavior with an actual spotlight remote. But you can already try out the version with command line toggle from the feature branch `feature/cmdline-spot-toogle` (compiled artifacts are attached to the ci build: https://github.com/jahnf/Projecteur/actions/runs/306563305)
