### ISSUE TITLE
can't install in F33

### ISSUE THREAD

**Issue by sia1984** [jahnf/Projecteur#117]
`dnf install projecteur` says:

```
nothing provides qt5 >= 5.7 needed by projecteur-0.9.0-alpha.66.x86_64
```

When I install it with `rpm -ihv --nodeps ./projecteur-0.8_fedora-32-x86_64.rpm` it works because qt5-qtbase is installed and this is apparently what Qt5 is called now. Projecteur itself works flawlessly, many thanks for this awesome application!

**Comment by jahnf** [comment]
Thanks for reporting. I will update the dependencies for fedora.
I will also mention it here, so you can test it before I merge that change to develop.

**Comment by jahnf** [comment]
Seems like the meta package that existed in Fedora 32 "qt5", is no more in Fedora 33

**Comment by jahnf** [comment]
@sia1984 Please give it a try with the attached Fedora-33 package attached to this automated build: https://github.com/jahnf/Projecteur/actions/runs/536417296

**Comment by sia1984** [comment]
This worked well and installed perfectly, thank you.
