### ISSUE TITLE
Feature Request: Please add option to disable compress of man page

### ISSUE THREAD

**Issue by ConiKost** [jahnf/Projecteur#126]
I am the maintainer of this package in Gentoo and in Gentoo, we have our own mechanism to compress man pages. This means, the package itself should always install the uncompressed man page and our package manager `portage` does this automatically while installing. The user can specify, in which format this happens.

I would like to have a switch, that the man page is not compressed during install.

**Comment by jahnf** [comment]
Hi Conrad, good to know - I created the compressed target as this is the default on Debian based systems. 
I will add an option - is a CMake option sufficient for that?

**Comment by ConiKost** [comment]
> I will add an option - is a CMake option sufficient for that?

Yes, this will perfectly do it! Since Gentoo is a source based distribution, it's will fit!

**Comment by jahnf** [comment]
I added the CMake option `COMPRESS_MAN_PAGE`,  e.g. usable at CMake configuration time with `-DCOMPRESS_MAN_PAGE=OFF` 
see 17531ee50b3c789004c9344a6b16a947e10a49a3

**Comment by ConiKost** [comment]
Thanks. Looks good. Tested and works.

**Comment by jahnf** [comment]
Perfect, and great that this little utility made its way to gentoo. Thanks for maintaining that package.
