### ISSUE TITLE
After vibration, Projecteur constantly uses one core

### ISSUE THREAD

**Issue by mayanksuman** [jahnf/Projecteur#133]
After vibration, the program constantly use one of core for 100% time.

To reproduce:
1. Open Projecteur and system monitor.
2. Connect Spotlight USB.
3. In Projecteur preferences,  go to device tab and select 'Vibration Timer'
4. Click 'Test' in Vibration settings.

The device will vibrate but this point onwards the application use one core continuously as visible in Gnome system monitor.

OS: Debian Testing
 - Desktop/Window Manager and Version: Gnome 3.28
 - Did you built _Projecteur_ yourself?: `[y/n]` n
 - What is the output of `projecteur -f` ?: ...
   Projecteur 0.9.1
    - git-branch: master
    - git-hash: 483d4a36e72de3c00f3d7f76207cc73e5a88a812
    - compiler: GNU 8.3.0
    - qt-version: (build: 5.11.3, runtime: 5.15.2)
    - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])

 - What is the output of `projecteur -d` ?: ...
   Projecteur 0.9.1; device scan

   * Found 1 supported devices. (1 readable, 1 writable)

   +++ name:     'Logitech USB Receiver'
       userName: 'Logitech Spotlight (USB)'
       vendorId:  046d
       productId: c53e
       phys:      usb-0000:04:00.3-2
       busType:   USB
       devices:   /dev/hidraw6, /dev/input/event22, /dev/input/event24, /dev/input/event23, /dev/input/event25
       readable:  true
       writable:  true

**Comment by jahnf** [comment]
Hi Mayank, thanks for reporting, I will see if I can reproduce this. Will request more info from your side if necessary.

**Comment by mayanksuman** [comment]
I think that calling `write` in [device-vibrate.cc:431](https://github.com/jahnf/Projecteur/blob/3b1693a7bdfd5e08d3c3a81c9c65ea579718fbc2/src/device-vibration.cc#L431) is causing this issue. [Flame graph](https://ibb.co/NYLrh43) generated for the application (using perf for 1 minute of activity) after the device has vibrated show a lot of system calls.
