### ISSUE TITLE
Logitech R500

### ISSUE THREAD

**Issue by TBK** [jahnf/Projecteur#15]
It seems Logitech released R500 as a cheaper alternative to the Spotlight.
https://www.logitech.com/en-us/product/r500-laser-presentation-remote

When installing Logitect Presentation on Windows you can chose your device (R500 | Spotlight).

I do not have a R500 available so I can test it with Projecteur, but I think it would be great if Projecteur could support both devices.

_Edit:_
Currently it does not make sense since the R500 does not have the "software pointer" and Projecteur does not provide an options to customize the button actions. If button customize is added then it would, since it has the next and back buttons.

**Comment by jahnf** [comment]
Yes, I also saw that the R500 doesn't have a "software pointer" because it probably has no gyroscope built in.  Hope it's okay to close this issue for now.

**Comment by TBK** [comment]
Yes, no problem  👍
