### ISSUE TITLE
Projecteur sorts the Spotlight Presets on start

### ISSUE THREAD

**Issue by mayanksuman** [jahnf/Projecteur#156]
**Description**
Projecteur 1.0 alpha is alphabetically sorting preset name in configuration file during start, which may lead to wrong preset order for the user. This may lead to surprises while cycling preset during presentation.

**To Reproduce**
Create a few spotlight presets and restart the projecteur. 

**Expected behavior**
Preset should be saved in the same order as user defined them, and Projecteur should not sort them automatically.

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Debian GNU/Linux bookworm/sid x86_64
 - Desktop/Window Manager and Version: GNOME 3.38.6 
 - Did you built _Projecteur_ yourself?: No (used prebuilt deb from cloudsmith)
 - What is the output of `projecteur -f` ?: 
 ```
Projecteur 1.0-alpha.97
  - git-branch: develop
  - git-hash: 2e75d28931635f20b65280f74ffcd73948a6982d
  - compiler: GNU 8.3.0
  - build-type: Release
  - qt-version: (build: 5.11.3, runtime: 5.15.2)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])
```
 - What is the output of `projecteur -d` ?: 
 ```
 * Found 1 supported devices. (1 readable, 1 writable)

 +++ name:     'Logitech USB Receiver'
     userName: 'Logitech Spotlight (USB)'
     vendorId:  046d
     productId: c53e
     phys:      usb-0000:04:00.3-2
     busType:   USB
     devices:   /dev/hidraw6, /dev/input/event8, /dev/input/event25, /dev/input/event23, /dev/input/event24
     readable:  true
     writable:  true
```

**Comment by mayanksuman** [comment]
This is the limitation of QSettings. If a user want to maintain a order then he can use numbers for same. For example, instead of naming a preset as 'Pointer' name it '1.Pointer'.

**Comment by jahnf** [comment]
> This is the limitation of `QSettings`. If a user want to maintain a order then he can use numbers for same. For example, instead of naming a preset as `Pointer` and `Highlight`, name it `1.Pointer` and `2.Highlight`, respectively.

Sounds good. And while there are endless possible settings for the spotlight overlay - I doubt that users will have more than 3 presets in real life situations :)
