### ISSUE TITLE
100% CPU on Pop!_OS 21.04 (v0.9.1)

### ISSUE THREAD

**Issue by FaKod** [jahnf/Projecteur#165]
**Description**
After a while projecteur uses up 100% of a core

**To Reproduce**
Pop!_OS 21.04 is bases on Ubuntu 21.04, so I assume thats an issue there too? Just wait a couple of minutes. I do not know if there is a specific trigger

**Expected behavior**
No CPU usage without moving mouse

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Pop!_OS 21.04
 - Desktop/Window Manager and Version GNOME 3.38.5 on X11
 - Did you built _Projecteur_ yourself?: `n`

**Comment by jahnf** [comment]
Thanks for you report - which version of _Projecteur_ are you using?
Please provide the output of `projecteur -f`

**Comment by FaKod** [comment]
0.9 and 0.9.1 - the old 0.8 I've used before did not move the mouse pointer anymore

**Comment by jahnf** [comment]
Thank you.

There was a fix in the current alpha versions for 1.0 regarding high cpu usage.
Could you try the current 1.0 alpha version and see if that behavior still occurs?

I plan to release the version 1.0 in a month or two, but then it can take a while until it shows up in the official ubuntu repositories (.. packagers have to pick it up, and then also the new version will probably only show up in newer ubuntu releases)

(If it is indeed the high cpu fix that fixes your issue I can think about creating a patch release 0.9.2, which then might show up in the official ubuntu repositories that currently ship 0.9.1.)

**Comment by jahnf** [comment]
Also you can you please try this package?:  (0.9.2 test build)
* https://github.com/jahnf/Projecteur/suites/3916804977/artifacts/97890548 

(from ci build: https://github.com/jahnf/Projecteur/actions/runs/1290122871)

**Comment by mayanksuman** [comment]
Hi @FaKod , 

You mentioned that you are not able to find a specific trigger event after which `Projecteur` uses 100% CPU.

For my case, the trigger event was device vibration (more details are available on #133 ). Can you please check in your case, if device vibration is the trigger event for high CPU usage.

If yes, then the fix is in `v0.9.2` hotfix release by @jahnf .

**Comment by FaKod** [comment]
Yes - that did the trick - thx
