### ISSUE TITLE
[BUG] fatal qml error

### ISSUE THREAD

**Issue by ralessi** [jahnf/Projecteur#166]
**Description**
As of commit [659b865] (Add support to build against Qt6)  `projecteur` crashes and issues a qml error as follows:

```
[2021-09-30T15:02:01.069][inf][projecteur.virtualdevice] Created uinput device: /sys/devices/virtual/input/input27
[2021-09-30T15:02:02.636][err][projecteur.mainapp] Overlay window error. ; Qml component has status '3'. Exiting.
[2021-09-30T15:02:02.636][err][projecteur.mainapp] qrc:/main.qml:78:45: Unexpected token `>'
[2021-09-30T15:02:02.636][err][projecteur.mainapp] qrc:/main.qml:80:24: Expected token `:'
[2021-09-30T15:02:02.636][err][projecteur.mainapp] qrc:/main.qml:80:61: Expected token `}'
```

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Devuan beowulf 3.1
 - Desktop/Window Manager and Version: awesome-wm + compton
 - Did you built _Projecteur_ yourself?: yes, but I also tried the packaged version.
 - What is the output of `projecteur -f` ?:
 ```
Projecteur 1.0-alpha.107
  - git-branch: develop
  - git-hash: 69d7eb59fb9ab8ad7a5599ac5979ea2f663ec1e3
  - compiler: GNU 8.3.0
  - build-type: Release
  - qt-version: (build: 5.11.3, runtime: 5.11.3)
  - device-scan: (errors: 0, devices: 0 [readable: 0, writable: 0])
```
 - What is the output of `projecteur -d` ?: 
```
Projecteur 1.0-alpha.107; device scan

 * Found 1 supported devices. (1 readable, 1 writable)

 +++ name:     'Logitech USB Receiver'
     userName: 'Logitech Spotlight (USB)'
     vendorId:  046d
     productId: c53e
     phys:      usb-0000:00:1a.0-1
     busType:   BusType::Usb
     devices:   /dev/input/event16, /dev/input/event15, /dev/input/event17, /dev/hidraw2, /dev/input/event14
     readable:  true
     writable:  true
```

Thank you for this excellent application which I use all the time! -- Robert

**Comment by jahnf** [comment]
Hey Robert,
I reverted a change in the qml file that obviously only worked with newer Qt versions.
Please let me now if your issue is fixed in the latest alpha version.

**Comment by ralessi** [comment]
> I reverted a change in the qml file that obviously only worked with newer Qt versions. Please let me now if your issue is fixed in the latest alpha version.

Indeed, this issue is fixed in the latest version.  Many thanks, Jahn!

**Comment by ralessi** [comment]
> I reverted a change in the qml file that obviously only worked with newer Qt versions. Please let me now if your issue is fixed in the latest alpha version.

Indeed, this issue is fixed in the latest version.  Many thanks, Jahn!
