### ISSUE TITLE
[BUG] Installing projecteur-0.9.2_ubuntu-20.04-x86_64.deb on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by holgerjakobs** [jahnf/Projecteur#171]
**Description**
When installing the above mentioned .deb file, the following output is generated, indicating an error.

`sudo dpkg -i projecteur-0.9.2_ubuntu-20.04-x86_64.deb 
Selecting previously unselected package projecteur.
(Reading database ... 508850 files and directories currently installed.)
Preparing to unpack projecteur-0.9.2_ubuntu-20.04-x86_64.deb ...
Unpacking projecteur (0.9.2-1) ...
Setting up projecteur (0.9.2-1) ...
Failed to write 'change' to '/sys/devices/virtual/input/input29/uevent': Cannot allocate memory
dpkg: error processing package projecteur (--install):
 installed projecteur package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 projecteur
`

iF  projecteur                                        0.9.2-1                               amd64        Linux/X11 application for the Logitech Spotlight device.

**To Reproduce**
Download .deb file and try to install.

**Expected behavior**
Installation should be completed.

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Ubuntu 20.04
 - Desktop/Window Manager and Version [e.g. Mate Desktop]
 - Did you built _Projecteur_ yourself?: `n`
 - What is the output of `projecteur -f` ?:
Projecteur 0.9.2
  - git-branch: master
  - git-hash: 82d9cfac1082a5cf28debb79a7be732fabf4dfd4
  - compiler: GNU 9.3.0
  - qt-version: (build: 5.12.8, runtime: 5.12.8)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])

 - What is the output of `projecteur -d` ?: 
Projecteur 0.9.2; device scan

 * Found 1 supported devices. (1 readable, 1 writable)

 +++ name:     'Logitech USB Receiver'
     userName: 'Logitech Spotlight (USB)'
     vendorId:  046d
     productId: c53e
     phys:      usb-0000:00:14.0-4
     busType:   USB
     devices:   /dev/input/event10, /dev/input/event8, /dev/input/event9, /dev/hidraw2, /dev/input/event7
     readable:  true
     writable:  true

**Comment by jahnf** [comment]
Thanks for your report. 
Since nothing with the packaging (done via CPack) changed this is strange.
I will look into it as I am also running 20.04 and can reproduce the issue.
