### ISSUE TITLE
[BUG] No Interactions on Ubuntu 21.10

### ISSUE THREAD

**Issue by eiswind** [jahnf/Projecteur#175]
**Description**
I installed projecteur-0.9.2_ubuntu-21.04-x86_64.deb, and updated my machine to 21.10.
w/o Projecteur running I can move the mouse and use the next/back button.
when I start projecteur, the highlight apperears when I press the button, but I cannot move it at all, also back/next shows no action.
Happens both on wayland and x11.

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: [e.g. Ubuntu 18.04]
ubuntu 20.10
 
- Desktop/Window Manager and Version [e.g. GNOME 3.28, KDE 5.4...]
 - gnome 40.4.0 on wayland or x11
 - 
 - Did you built _Projecteur_ yourself?: `[y/n]` no
   _(If yes: Please run cmake for existing build directories, to ensure the generated version info is up to date)_

 - What is the output of `projecteur -f` ?: ...
Projecteur 0.9.2
  - git-branch: master
  - git-hash: 82d9cfac1082a5cf28debb79a7be732fabf4dfd4
  - compiler: GNU 10.2.1
  - qt-version: (build: 5.15.2, runtime: 5.15.2)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])
 
 - What is the output of `projecteur -d` ?: ...
 Projecteur 0.9.2; device scan

 * Found 1 supported devices. (1 readable, 1 writable)

 +++ name:     'SPOTLIGHT'
     userName: 'Logitech Spotlight (Bluetooth)'
     vendorId:  046d
     productId: b503
     phys:      64:6e:e0:5a:27:e1
     busType:   Bluetooth
     devices:   /dev/input/event21, /dev/input/event20
     readable:  true
     writable:  true

**Comment by jahnf** [comment]
Hi @eiswind  - thanks for the report - so you had Ubuntu 21.04 running with Projecteur and updated to 21.10 - did I get that right?

**Comment by eiswind** [comment]
Yes. I had some older version of projecteur on 21.04, updated to 0.9.2 when I found that it doesn't work anymore, but that did not help ... :) Let be know if I can be of any assistance.

**Comment by benneti** [comment]
same thing happening on NixOS with gnome 41.1 (on wayland) with 0.9.2 as well as https://github.com/jahnf/Projecteur/pull/173

**Comment by jahnf** [comment]
Thank you for reporting. In the last few months I could not pay much attention to the project.
Question @benneti, did you test it with the latest version from the `develop` branch? 
for #173 - on that feature branch unfortunately nothing has happened yet. 🙁

**Comment by benneti** [comment]
I just double checked with https://github.com/jahnf/Projecteur/commit/21e5e606ff2fb5daf712d66fc2a77cdb7aa3cdde and the cursor still does not move.
Maybe it is similar to this problem: https://github.com/Plagman/gamescope/issues/33 and https://bbs.archlinux.org/viewtopic.php?id=228032 .

If it is something like that, an option to keep the os device of the mouse and disable the virtual mouse would be a simple workaround.

**Comment by benneti** [comment]
or could it be related to the normalization of the virtual device: https://wayland.freedesktop.org/libinput/doc/latest/normalization-of-relative-motion.html

**Comment by markoott** [comment]
Any news at this point. Would love to use your tool but unfortunately it's not working (same as above) in ubuntu 21.10 :-/

**Comment by jahnf** [comment]
Yes, sorry I couldn't allocate time for _Projecteur_.

So it seems it is a two-folded problem. 
* wayland
* Ubuntu 21.10 (and probably 22.04) even with X11

I will need to install 21.10 in a VM and do some issue tracking.

A question for users on X11 on Ubuntu 21.10:
* Does it work if you start the program with `--disable-uinput`? (This will essentially also disable custom key mappings)

**Comment by benneti** [comment]
Ah thanks `projecteur --disable-uinput` works for me on wayland (with the normal circle pointer)!

**Comment by jahnf** [comment]
> Ah thanks `projecteur --disable-uinput` works for me on wayland (with the normal circle pointer)!

Good to know, of course the nice feature of mapping custom inputs is disabled 😞  - so this is only kind of a workaround. Seems one issue is around the area of grabbing all the device input and feeding it (mapped) to a virtual uinput device. That definitely narrows down my issue tracking.

**Comment by benneti** [comment]
indeed, but it is far better than a pointer that does not move :sweat_smile:

**Comment by jahnf** [comment]
Now that Ubuntu 22.04 is released I will check with that release and see if anything from earlier versions changed in regards to the  `uinput` device handling.

**Comment by jahnf** [comment]
It is definitely related on how to `uinput` and wayland on newer distribution releases. Sadly I do not have a quick fix or workaround at the moment. I need to see how other projects might solve this issue.

**Comment by utuser** [comment]
I know such time problems too well...... So thanks a million that the tool exists at all with such comprehensive functionality!

Yes, I can confirm that in a regular 22.04-setup (no vm, fresh install yesterday). On 18.04 it works out of the box with your binary. On 22.04 the above workaround is necessary. However, it is strange that everything worked during the very first start-up on 22.04. Then I switched to Win10 (dual boot machine), installed the respective app and configured the device. Back in 22.04 no movement anymore. The Pointer with all features is displayed though. Maybe this is a useful additional information or just coincidence?

**Comment by utuser** [comment]
@khalil-i-o, thats a great idea. @jahnf: You are very welcome to contact me too if testing is necessary.

**Comment by Blaimi** [comment]
I did some investigation and found out something interesting.
I recorded the movement with `libinput record /dev/input/event## > file.yml` and compared the records from the original with moving cursor and from the virtual device without a moving cursor.
`libinput replay file.yml` did what anyone would expect: when replaying the record of the original device, the cursor moves, replaying the virtual device doesn't move.

BUT: If you change the line in the record file of the virtual device at position `devices[0].codecs.1` (EV_KEY) to the same value given in the record of the original device, the cursor moves when replaying. Yaaay! (i.e. [272..287] instead of [1..767]). To get rid of the upcoming warning `device is missing recorded udev property`, I tried [1..287] and it still works but without this kind of warning (I still get the warning `unexpected property: LIBINPUT_DEVICE_GROUP` but I guess, this is a different topic)

I don't know if this helps figuring out what the actual problem is, but I hope it helps a little ;)

Oh, BTW: running fedora 37 workstation on gnome 43.2 with wayland and rpm-installation.

**Comment by jahnf** [comment]
Wow thank you for the detailed investigation - that is very useful - I will use your input to create a fix!!

**Comment by jahnf** [comment]
@Blaimi @benneti @eiswind @markoott 

If possible please test a version build from the https://github.com/jahnf/Projecteur/tree/bugfix/input-virtualdevice branch.
I integrated the results of @Blaimi 's investigation.

 Thank you very much in advance

**Comment by benneti** [comment]
sorry for the late reply, tested it now on several occasions and so far the new branch is working great for me with gnome+wayland.
