### ISSUE TITLE
QML component error in 0.9.2

### ISSUE THREAD

**Issue by gyps** [jahnf/Projecteur#178]
Dear all,

today I rebuild projecteur 0.9.2 on my guix system. About a month ago everything worked fine but now the newly build program complains

`[err][projecteur.mainapp] Overlay window error. ; Qml component has status '3'. Exiting.`

It definitively has to do with changes on my system, but I have no clue what to look for. All qt packages seem to be in version 5.15.2 (I have no idea what version they were when it still worked).
```
guix package --list-installed | grep qt
qtbase              	5.15.2              	out	/gnu/store/3ag62qr53br83x0p0739xdhshd3km7yk-qtbase-5.15.2
qtdeclarative       	5.15.2              	out	/gnu/store/49rn4wjbwaagb8hr6rgdgwdm6bbdab6x-qtdeclarative-5.15.2
qtx11extras         	5.15.2              	out	/gnu/store/vsdx1mp5fp8ngqa4flm2vfpi723wj6q8-qtx11extras-5.15.2
qtgraphicaleffects  	5.15.2              	out	/gnu/store/22jq16rmk7rj5yi9sr01m9nic94k1jdp-qtgraphicaleffects-5.15.2
qtquickcontrols2    	5.15.2              	out	/gnu/store/yw5fj3hjdv9wg8wr2ax4rgh8xslwf1p5-qtquickcontrols2-5.15.2
```

Any idea? Thanks,
Alex

**Comment by jahnf** [comment]
Hi Alex this sounds familiar. Are you building against the the same Qt version? (E.g. against 6 instead of 5?)  But I can only check on my system from Monday on.

**Comment by gyps** [comment]
I tried both. First qtbase was in version 6 but then I forced it be be 5 on my whole system (as can be seen in the previous post). I'll check if it was *really* linked against the right version of the library.

**Comment by jahnf** [comment]
You can also see the compile and runtime versions used with `projecteur -f` on the command line.

**Comment by gyps** [comment]
OK, I've done that but the result is strange. 
```$ projecteur -f
Projecteur 0.9.2
  - git-branch: master
  - git-hash: 82d9cfac1082a5cf28debb79a7be732fabf4dfd4
  - compiler: GNU 10.3.0
  - qt-version: (build: 5.15.2, runtime: 5.15.2)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])
 ```
Then I tried projecteur in my current generation of my system
```
$ projecteur 
[2022-01-10T10:51:22.073][inf][projecteur.virtualdevice] Created uinput device: /sys/devices/virtual/input/input55
[2022-01-10T10:51:22.238][inf][projecteur.device] Connected device: Logitech Spotlight (USB) (046d:c53e)
^C
```
and it starts up parfectly fine.

Next I switched back to the generation it didn't work in and tried the same:
```$ guix package --switch-generation=178
switched from generation 184 to 178
$ projecteur -f
Projecteur 0.9.2
  - git-branch: master
  - git-hash: 82d9cfac1082a5cf28debb79a7be732fabf4dfd4
  - compiler: GNU 10.3.0
  - qt-version: (build: 5.15.2, runtime: 5.15.2)
  - device-scan: (errors: 0, devices: 1 [readable: 1, writable: 1])
$ projecteur 
[2022-01-10T10:52:50.729][inf][projecteur.virtualdevice] Created uinput device: /sys/devices/virtual/input/input56
[2022-01-10T10:52:50.809][err][projecteur.mainapp] Overlay window error. ; Qml component has status '3'. Exiting.
[2022-01-10T10:52:50.877][inf][projecteur.device] Connected device: Logitech Spotlight (USB) (046d:c53e)
```
There seems to be no difference. Very strange!

**Comment by jahnf** [comment]
I'm not sure exactly what you refer to as 'generation' - but with builds a lot of times it is best to throw away the build directory and create a new one to make sure no CMake cache variable has unintended side effects.

**Comment by jahnf** [comment]
closing this for now
