### ISSUE TITLE
Disable Git for version check.

### ISSUE THREAD

**Issue by ConiKost** [jahnf/Projecteur#18]
Currently, even on normal release, a Gitcheck is run to determinate version.
So on a release zip, this will fail and produce a 0.0 version.

This check should depend on CMAKE_BUILD_TYPE =! Release or something like this.

**Comment by jahnf** [comment]
You are right, the build should work without being within a git repository. (It has nothing to do with the CMAKE_BUILD_TYPE though). I will look into it.

**Comment by jahnf** [comment]
2ba77b9c118dfae82e1763ddb2399f7718d4c677 should fix this issue, at least for (zip) archives for the current develop branch and future releases. While a version is now generated it is not as detailed as when building with sources from within the git repo. 

If there are still issues feel free to comment and re-open.

**Comment by ConiKost** [comment]
Great! Many thanks. Works fine here.
