### ISSUE TITLE
Feature Request: Starting / adjusting a timer from command line, or triggering vibration externally.

### ISSUE THREAD

**Issue by gbdlin** [jahnf/Projecteur#202]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to adjust or start/stop a timer externally. There is no way either to trigger a vibration. In certain situations it'd be useful to start the timer automatically when for example you open some software. It is also useful to trigger the vibration event externally.

**Describe the solution you'd like**
There should be a way to at least trigger a vibration externally, so for example some notification may end up as a vibration alert, or there would be ability to create an external timer software. Ideally, there should be a way to set up timers inside the software as well from the command line or any API.

**Describe alternatives you've considered**
No workarounds really exist.

**Comment by jahnf** [comment]
Hello thank you for the request. Sound like a good idea. And actually quiet straightforward to implement (in comparison to all the issues with Wayland... :) )

**Comment by jahnf** [comment]
- [ ] Device vibrate command via command line (https://github.com/jahnf/Projecteur/pull/211)
- [ ] set/adjust timers via command line 
- [ ] start a specified timer via button mapping
