### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by drupol** [jahnf/Projecteur#203]
Hello, 

It's been 2 years since the last release, and commits were made on the branch.

Do you think you could create an intermediary tag before 1.0.0 ?

Thanks.

**Comment by jahnf** [comment]
hi, yes I kind of abandoned the project for quite a while (one reason are the issues with Qt and Wayland and how this project uses features of Qt with X11 that don't work with Wayland anymore/not yet) 

I am however totally fine with releasing a 0.10.0

**Comment by drupol** [comment]
So sad to hear you abandoned the project... it's totally useful and there's no other software doing that !

I'm glad that a new release will be soon out, I will provide the update for NixOS.

If you plan to come back to this project, please implement a highlighter pencil that would be disappearing after a couple of seconds, it would be so useful!

**Comment by jahnf** [comment]
I will plan a release (`0.10.0`) with all the current changes and fixes on develop - rough guess within in a month.
(Making projecteur completely work with wayland is out of scope currently)
In addition the some of the feature requests I like might get into this release.
