### ISSUE TITLE
Black rectangle instead of spotlight

### ISSUE THREAD

**Issue by ralessi** [jahnf/Projecteur#22]
I just built and installed the latest Projecteur (0.6 alpha2), but instead of the expected spotlight, hitting the lens button gets me a black rectangle stuck at the top left corner of the screen as shown in the attached screenshot.  I use awesome-wm; under windowmaker, I get the same result, while mate just renders nothing.

Any advice would be much appreciated.  Many thanks for providing this!

![screenshot](https://user-images.githubusercontent.com/389498/59375498-93507580-8d4e-11e9-9724-52a48e62be98.png)

**Comment by jahnf** [comment]
Hi @ralessi, to narrow down what the issue might be:  What Linux distribution/version are you running?
Also it would be helpful if you could give me feedback on if you build v0.4 and check if that version is working for you.

Besides that: Are OpenGL programs run on your machine? (QtQuick utilizes OpenGL) - How are Windows of other programs behave that have transparency (e.g. transparent console window)
I don't know awesome-wm but I found this regarding awesome-wm and transparent windows which might be related: https://github.com/awesomeWM/awesome/issues/2473#issuecomment-437302625

**Comment by ralessi** [comment]
I run Hyperbola (https://www.hyperbola.info/) which is based on Arch.

Unfortunately, v0.4 does not build on my system. `make` fails on errors such as:
````
/home/robert/projecteur/projecteurapp.cc:124:15: error: 'class QWindow' has no member named 'setFlag'; did you mean 'setFlags'?
       window->setFlag(Qt::WindowStaysOnTopHint, true);
               ^~~~~~~
````
I will do a bisect and report back on the first version that compiles.

As for OpenGL, I have mesa of course, and I can say that transparency works fine with the Guake terminal.

Regarding awesome, I will check the pointer.  But as said, Projecteur doesn't work on my system under mate wm.

**Comment by ralessi** [comment]
[e109f4b] compiles, while [de02c70] doesn't. And [de02c70] gives me the black rectangle stuck on the top left corner of the screen.

**Comment by jahnf** [comment]
Thanks. Could you please try to build the latest develop with replacing `qml/main.qml` for the `main.qml` from **v0.4** (https://github.com/jahnf/Projecteur/blob/v0.4/qml/main.qml) - I have a hunch that it might be related to the changes within that qml file - at least for some systems.

**Comment by ralessi** [comment]
Same black rectangle with `main.qml` from v0.4, but with a notable difference: when I move the pointer over the rectangle, the goes _under_ the rectangle and so gets hidden.  With the latest `main.qml`, it is the other way round: the pointer remains visible above the rectangle.

Running `./projecteur` is perfectly clean: no errors at all...

**Comment by ralessi** [comment]
Good news: I managed to make Projecteur work with Mate.  I would like to run some further tests tomorrow, but I will report back very shortly.  Meanwhile, many thanks from a grateful user!

**Comment by ralessi** [comment]
To sum up, this was almost all about transparency.  I installed `compton`, launched it with `compton -b` and Projecteur worked as expected with awsome.  The only glitch—if I must say so—is that at least a second monitor must be connected.  Otherwise, `compton` makes the black rectangle go but the only thing I get is the mouse pointer.

For Projecteur to work, `compton` being launched as a daemon, I have to select the second screen. Then, everything works fine: I am even able to select back the first screen which didn't work in the first place.

I still have to perform a test of Projecteur under real conditions in a room equipped with a video projector, bu I think we can close this issue.

With many thanks again, I am very happy with Projecteur!
