### ISSUE TITLE
Feature Request: mouse support?

### ISSUE THREAD

**Issue by TLINDEN** [jahnf/Projecteur#225]
Would it be possible to use the mouse as pointer device? The idea would be to temporarily turn on the spotlight using a key binding (which seems to be supported already) and the use the mouse to move the spotlight.

The use case is an online presentation where the mouse is required and no special pointer device is available.

Would that be possible?

**Comment by jahnf** [comment]
Helllo, yes it is possible already 

basically any "mouse"/pointing device can be used with the command line option `-D`, see https://github.com/jahnf/Projecteur?tab=readme-ov-file#command-line-interface.

But I guess what you are looking a way to enable/disable the spotlight with a keyboard shortcut.
There is also a command line option for this. With a running _Projecteur_ instance you can enable/disable/toggle the spot.
For example `projecteur -c spot=toggle` / also see https://github.com/jahnf/Projecteur?tab=readme-ov-file#command-line-interface. (If the spot overlay is visible it reacts to any "mouse" pointer movement). 

(The device integration in Projecteur simply enables and disables the spot overlay depending on movement for certain enabled devices)

You can bind the toggle spot command to any shortcut you desire (how you do that differs with every Linux Desktop environment).
hope that helps.

**Comment by TLINDEN** [comment]
Oh, wow, this is amazing! Works like a charm, yeah :)

Thanks a lot for this tool, comes very handy. Cool!


best regards,
Tom
