### ISSUE TITLE
Device ID for smartphone gyroscope/mouse emulators

### ISSUE THREAD

**Issue by thdesy** [jahnf/Projecteur#29]
Hi,

afais changing the device ID should be doable by changing the ID string, or? 

I just thought about, if one could use Projecteur in connection with a smartphone.

There seem to be a number of mouse emulators for Android out there, translating gyroscope data into mouse movements.
On a quick search, most apps seem to be closed source and rely on client/server approach via Wifi. But I have not given up to find something Bluetooth based (if a phone could be paired on a Bluetooth input device profile without rooting...)

**Comment by jahnf** [comment]
Neat idea, especially since everybody carries around these devices. I would still prefer the form factor of the Logitech device for doing a presentation, but it is way overpriced in my opinion.
May your search be successful :)

**Comment by thdesy** [comment]
yes, while I have a Spotlight myself, something more 'generic' would be nice ;)

unfortunately, I found only client/server solutions so far relying on a wifi/network - which might bring all kind of pitfalls. Have to see, if there is a rooting way... ;)

I am closing the issue, as it seems to be more complicated on the Android site of things ;)
