### ISSUE TITLE
Projecteur on Debian 10

### ISSUE THREAD

**Issue by ImplicitDeny** [jahnf/Projecteur#30]
I downloaded the .deb file for Debian 9, hoping it to work on Debian 10 (KDE Plasma Desktop). Unfortunately, something is wrong somewhere. When going to Projecteur settings, the "Device connected:" field always display "false". Is there any obvious difference between Debian 9 and 10 explaining this behaviour ?

I'll try to build it by myself later on.

**Comment by jahnf** [comment]
Hi, seems more like an issue with the udev rules (that should be installed with the package though) than the application itself. Do you use the USB dongle or do you connect via Bluetooth?

**Comment by ImplicitDeny** [comment]
Thanks for you answer. I'm using the USB dongle, I just tried linking it via Bluetooth but it seems that my laptop don't see it in the peripherals list. I don't have much time to investigate this problem today, though.

I'm afraid that this file doesn't exists at all. That might be the core of the problem.

**Comment by jahnf** [comment]
The rules file define which user-group have access to the spotlight device, which is `GROUP="spotlight-device"` by default. So you will need to add yourself to that group.

**Comment by ImplicitDeny** [comment]
Oh perfect, I indeed added a proper group and now everything is working as expected. Thanks a lot !
