### ISSUE TITLE
Use with other devices

### ISSUE THREAD

**Issue by evazzoler** [jahnf/Projecteur#31]
Please, add the ability to choose from menu the device used as "mouse presenter". This way people could use "other" (non Logitech) cheaper devices...
This way the software would become "universal" and no Logitech locked.
Thank you for your attention.

**Comment by jahnf** [comment]
Compile time possibility added (see `devices.conf`) & command line option `-D` added. Also see https://github.com/jahnf/Projecteur#device-support for details.
