### ISSUE TITLE
No Transparency in EXWM

### ISSUE THREAD

**Issue by gyps** [jahnf/Projecteur#50]
Hi all,
I was using Projecteur for some time on gnome desktop and was really satisfied with it (a really really stable application!). 
Now I'm using EXWM as window manager (since I spend most of my time in emacs anyway, it's really convenient) and would like to continue using Projecteur to present my lectures. Unfortunately the result looks as shown in the following picture (I set the shade color to red and dot color to yellow to show the effect):
![IMG_1869](https://user-images.githubusercontent.com/4351605/68834498-dfad3200-06ad-11ea-8422-92c645d92892.jpg)
instead of:
![IMG_1870](https://user-images.githubusercontent.com/4351605/68835062-23ed0200-06af-11ea-98f9-c713f3dbb961.jpg)

To me it seems as if the fullscreen window where the spotlight and pointer are shown in is supposed to be 100% transparent but is completely black when using EXWM. So everything is not shown in front of the presentation but on top of a black layer above the presentation. Can this be correct? Does anybody have an idea how this issue could be resolved?
Thanks in advance,
Alex

**Comment by jahnf** [comment]
Hi @gyps, please have a look at issue #10 , do you have a compositor running? (Necessary for transparency)

**Comment by jahnf** [comment]
Note to self: Definitely put info about compositing manager in README.md and see if there is a non-intrusive way to warn the user like in pull request #37

**Comment by gyps** [comment]
I suppose not. EXWM seems to support third party compositing managers. 
I never used one any suggestion which one to use?

**Comment by jahnf** [comment]
I personally use mostly GNOME and sometimes KDE or Xfce - so I can't give you a suggestion here - hopefully somebody else. In https://github.com/ch11ng/exwm/issues/24 somebody mentions `xcompmgr` - you could try that.

**Comment by gyps** [comment]
Thanks. Just running "xcompmgr -c &" before or after starting projecteur solved the issue. Works like a charm!
