### ISSUE TITLE
No spotlight shown after switching application to fullscreen

### ISSUE THREAD

**Issue by gyps** [jahnf/Projecteur#51]
**Description**
No spotlight shown when switching application to fullscreen. Restart of projeceur necessary after switch to fullscreen

**To Reproduce**
1. Start projecteur
2. open browser non-fullscreen
3. use spotlight successfully
4. switch to fullscreen
5. Unexpected: spotlight acts as pointer (i.e. mouse) not as spotlight
6. restart projecteur
7. spotlight acts as expected (also in fullscreen) 
8. goto 2

**Expected behavior**
No change when switching application to fullscreen

**Desktop/Linux Environment (please complete the following information):**
 - Linux Distribution and Version: Debian testing/bulleseye
 - Desktop/Window Manager and Version EXWM on gnome-flashback with xcmpmgr
 - Qt Version:qt5.12.5
 - Did you built _Projecteur_ yourself?:y
 - What is the output of `projecteur -f`: 
> Projecteur 0.6-alpha.70
>  - git-branch: develop
>  - git-hash: b1377707d60503e98feb2d27d8320331898b6093
>  - compiler: GNU 9.2.1
>  - Qt-version: build: 5.12.5, runtime: 5.12.5

**Comment by jahnf** [comment]
Hi @gyps, thanks for your bug report - at least on a GNOME Desktop I have currently access to, I cannot reproduce this. In my case the spotlight-window is always on top of the full-screen browser (tried with Firefox and Chrome) 
Which browser are you using?

**Comment by gyps** [comment]
I tired with my presentation app xounalpp as well as icecat

**Comment by gyps** [comment]
The interesting thing is, that after reastart everything works fine (even in fullscreen) but switching to nonfulscreen and back to fullscreen reproduces the problem. 

Is there any point in the source where I could start debugging (I have to admit thought that it's 15 years since I programmed in C++ the last time).

Cheers,
Alex

**Comment by jahnf** [comment]
Okay, just a guess at this time, but it could be that the window flags that work with other window managers don't work the same with EXWM and Qt's `showFullScreen()` seems not to have the desired effect with EXWM to be placed above all existing windows.
You could try to add an extra `window->raise()` after line 152 `projecteurapp.cc` (after `window->showFullScreen();`)

**Comment by gyps** [comment]
Perfect! Adding raise() solved the issue - Thanks!
-- Alex

**Comment by gyps** [comment]
Will you add the change into the git-master?

**Comment by jahnf** [comment]
Thanks for testing! Yes I will add it to the repo, of course after making sure _Projecteur_ behaves still as expected on the main Desktop environments (GNOME, KDE...)

**Comment by jahnf** [comment]
@gyps Could you please build the [bugfix/fullscreen-on-exwm](https://github.com/jahnf/Projecteur/tree/bugfix/fullscreen-on-exwm) branch and test it.
There is also a second commit on that branch, that should show a warning in the preferences dialog if no compositing manager is running - could you please test if that warning shows up correctly too?

**Comment by gyps** [comment]
Works fine. Switching back and forth between fullscreen and non-fullscreen works. 
Starting and killing xcompmgr in a warning (or not if running). 
Compiling without libqt5x11extras5-dev installed doesn't raise a warning thought. Maybe this should be the case?

**Comment by jahnf** [comment]
:+1:  Thank you  very much.
About the 'missing' compilation warning: Since there are users that don't use X11 (maybe Wayland or other) - I made it possible to build the project without the x11extras on purpose.
