### ISSUE TITLE
AUR Package for Arch Linux

### ISSUE THREAD

**Issue by m4dz** [jahnf/Projecteur#53]
Hi there!

thanks for the good work on this app!

I've just published a package for the [_upstream_ version on AUR](https://aur.archlinux.org/packages/projecteur-git/), so the package is available to all Arch Linux users from their package manager. I'll maintain it stick to the `develop` branch.

Thanks again 👋 !

**Comment by jahnf** [comment]
Oh cool very nice :+1: 
I have a question about the version number though: woyldb

**Comment by jahnf** [comment]
The files `version-string` and `version-string.archlinux` are created now during the CMake run, which would allow you to run CMake during [prepare()](https://wiki.archlinux.org/index.php/Creating_packages#prepare()) and use the `version-string.archlinux` file in [pkgver()](https://wiki.archlinux.org/index.php/creating_packages#pkgver())


```
prepare() {
  mkdir -p "$srcdir/build"
  cd "$srcdir/build"
  cmake "$srcdir/$_gitname"
}

pkgver() {
  cd "$srcdir/build"
  cat ./version-string.archlinux
}
```

**Comment by m4dz** [comment]
Great!

As Arch provides some guidelines for [VCS Packages](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function), I've used the `version-string.archlinux` and append the git distance and commit hash. It works great!

I also published a [regular version](https://aur.archlinux.org/packages/projecteur) for the latest release based on tag.

Thanks for tha good work!

**Comment by jahnf** [comment]
Upvoted your AUR packages :)
