### ISSUE TITLE
Redesign of preferences dialog box

### ISSUE THREAD

**Issue by mayanksuman** [jahnf/Projecteur#56]
With increasing number of settings, the current preferences dialog box may become cluttered. For instance, options for pointer modes (#38), timer (#6), modifying Next/Back keystroke (#43) and their hold events will be added in the future, which require a redesign of preference dialog box.

I think, following two steps are necessary for fixing this issue:

1. Separate `SpotAreaSettings` (all options related to spot) class and its instances are member of `Settings` class: This will also help us in defining different Pointer modes.
2. Redesign preferences dialog box using tabs (preferably in QML)

What do you think? I will be posting mockups  of the dialog box soon.

**Comment by jahnf** [comment]
Regarding the Setrings, there needs to be a restructuring, especially when supporting multiple devices. (The code right now already allows for multiple devices to be connected at the same time. But put that aside for the moment.

A mock up will be a good base for discussion. And also will make it clearer to see how to group things in code. We will definitely need tabs.

As for Qml in the dialog: I would keep that aside for the time being also. Too many changes at once. Converting an existing good dialog to a "stylish" Qml dialog can always be done later.

**Comment by mayanksuman** [comment]
@jahnf I have made some quick mock up on https://app.moqups.com/RcJABMoumb/view/page/a990a1a38

The visual design (mock up is a bit towards mobile side) do not matter. The important point is we need to two level tab for Pointer mode. The parent tab bar can be vertical or in side (mock up show vertical placement).

**Comment by jahnf** [comment]
Cool thanks, I like it - I have only minor things to add. Is it possible to make annotations on on that mock-up page?

It's great that you are eager contribute, for the implementation of the updated preferences dialog I'd like you to wait until I have restructured the code for multiple devices (also one device can have one or multiple input devices (e.g. for mouse and keyboard events) and all that it affects..
During the holidays I will have time for restructuring.

**Comment by mayanksuman** [comment]
> Cool thanks, I like it - I have only minor things to add. Is it possible to make annotations on on that mock-up page?
You can comment on the mockup page with your google/moqups account.

> It's great that you are eager contribute, for the implementation of the updated preferences dialog I'd like you to wait until I have restructured the code for multiple devices (also one device can have one or multiple input devices (e.g. for mouse and keyboard events) and all that it affects..

Currently, `spotlight.cc` only connect to mouse HID. I was thinking of adding keyboard support. 

I can wait till the restructuring is over.

**Comment by mayanksuman** [comment]
This issue is quite old and the preferences dialog box has changed a lot.

I am closing this issue as it is not relevant any more.
