### ISSUE TITLE
Feature: RHEL8 RPM Build

### ISSUE THREAD

**Issue by aclater** [jahnf/Projecteur#66]
I was able to compile projecteur on RHEL8 and it seems to be working.  I had to install a few QT libraries, but it works. There was a bit of ham fisted grasping at QT packages, but I could probably produce a list of required RPM's if someone wanted to undertake the effort.

**Comment by jahnf** [comment]
Yeah why not. But I would definitely need a docker RHEL8 docker image for that (all the package builds are automated via docker on their respective distribution images) - do you know if there is one?

**Comment by aclater** [comment]
https://developers.redhat.com/products/rhel/ubi/

**Comment by jahnf** [comment]
Found this which seems a good start on creating a RHEL8 based docker image: https://medium.com/pareture/docker-basics-dockerised-rhel8-24d49d93e91d

**Comment by jahnf** [comment]
I might add that a RHEL8 package build does not have a really high priority on my personal list. Contributions are welcome though: Very helpful would be:
* a docker image that can build the project and the `dist-package` target, similar to the existing build images (see: https://github.com/jahnf/Projecteur/tree/develop/docker) 
* and a minimal list of package dependencies that will be needed at runtime on a fresh installed distribution - similar to existing ones in https://github.com/jahnf/Projecteur/blob/develop/cmake/modules/PkgDependenciesProjecteur.cmake

**Comment by aclater** [comment]
Installing a vanilla RHEL8 VM to get the package list together.

**Comment by aclater** [comment]
On a vanilla RHEL8 Developer free subscription (https://developers.redhat.com/topics/linux/)

Connect RHEL to RH repos using your dev credentials:
sudo subscription-manager register
sudo subscription-manager refresh
sudo subscription-manager attach --auto

sudo dnf -y install qt5-qtbase qt5-qtbase-devel qt5-qtgraphicaleffects qt5-qtx11extras qt5-qt3d-devel qt5-qt3d make cmake git

# this installs a whole bunch of dependencies

sudo git clone https://github.com/jahnf/projecteur
sudo mkdir build && cd build
sudo cmake ..
sudo make
sudo make install
sudo cp 55-spotlight.rules /lib/udev/rules.d/55-spotlight.rules
sudo udevadm trigger

# Projecteur doesnt run in the VM, but I *think* that's a VM / X display complication. The same steps work on my laptop.

Looking into some gotchas for building this into a container w/UBI

**Comment by jahnf** [comment]
@aclater 
Thanks for the details. I tried to create a docker build image for _Projecteur_ based on RHEL8 yesterday (like described here https://medium.com/pareture/docker-basics-dockerised-rhel8-24d49d93e91d) but realized, that you can only get qt5 packages with a subscribtion.

This makes it basically not possible to create a docker image (which will be publicly available) for automated builds. The only thing that I could do is to add package information for RHEL8, so that RHEL8 users could run `make dist-pkg` and it would build a *rpm*-package

**Comment by jahnf** [comment]
@aclater Would a package that was built on CentOS 8, work on RHEL8?

**Comment by aclater** [comment]
It should - I'm happy to test

**Comment by jahnf** [comment]
Alright: here you go, please try it out- the latest builds have a build for CentOS-8 and also create a package for it:
* Build: https://travis-ci.org/jahnf/Projecteur/jobs/650472852?utm_medium=notification&utm_source=github_status
* Binaries: https://bintray.com/jahnf/Projecteur/projecteur-develop/0.7-alpha.29#files

**Comment by aclater** [comment]
Biary works for me! Thanks a million. I'll be sure to let other folks @ Red Hat know this is available.

**Comment by jahnf** [comment]
Perfect, great that it works. Also happy to see that _Projecteur_ being used on a variety of distributions. All future versions will now be additionaly build on CentOS (763632e)
