### ISSUE TITLE
Change presenter mode via double click

### ISSUE THREAD

**Issue by migoller-upb** [jahnf/Projecteur#68]
The original Logitech driver under Windows / MacOs allows to change the presenter mode via double click on the first button of the device. This way it can be alternated between Zoom, Spotlight and Center Dot.

At this moment, I am inclined to return the presenter that I just bought because this is an essential feature for me.

So is it possible to build in this double-click feature?

Many thanks!

Michael

**Comment by jahnf** [comment]
This feature, as well as #43 and #58 will be covered in #69

**Comment by jahnf** [comment]
With the latest changes you can now assign a "Cycle Presets" action to a button input sequence.
This allows you to have as many "presenter modes" as you like and cycle through them.
