### ISSUE TITLE
spotlight update broken under wine powerpnt fullscreen

### ISSUE THREAD

**Issue by fmuelle4711** [jahnf/Projecteur#72]
**Description**
When running powerpnt in full screen (F5) presentation mode under wine,
the spotlight shows up initially but does not follow move movements.
When move is stopped and after a wait moved again, spotlight shows at the new mouse position
but still does not follow mouse movement. The mouse cursor meanwhile is still moving.

I suspect a QT5/Wayland problem. Investigating a work around, I noticed that if I change the spotlight.cc code to always call emit spotActiveChanged(true) -- even if the timer is already active -- the spotlight tracks the move but updates are too slow and the spotlight is blinking (active on/off). Is there another QT5 method to more gracefully update the spotlight (lower overhead in repainting)?

Notice that the problem is unique to wine fullscreen. OpenOffice or other fullscreen apps don't show this problem.

**To Reproduce**
QT_QPA_PLATFORM=xcb ./projecteur -D "some device" 

**Expected behavior**
Shoptlight should track mouse movement.

**Desktop/Linux Environment (please complete the following information):**
fedora 31
gnome 3.34.2-1.fc31 wayland xcb
qt5-5.13.2-1.fc31
old wine-staging-3.6-1
Did you built _Projecteur_ yourself?: y but does not matter
Projecteur 0.7-alpha.40
  - git-branch: develop
  - git-hash: e2b24031ccdf7ce2de995aa7395eb853c49ae5cb
  - compiler: GNU 9.2.1
  - qt-version: (build: 5.13.2, runtime: 5.13.2)
  - device-scan: (errors: 0, devices: 0 [readable: 0, writable: 0])
(Works w/ device 2:a trackpointer, uinput or any external mouse)

**Screenshots**
cannot show that way

**Comment by fmuelle4711** [comment]
Never mind, I tracked it down to a wine. issue. You may close it.

**Comment by jahnf** [comment]
Thank for reporting and investigating

**Comment by fmuelle4711** [comment]
Looks like I was wrong. The problem goes away when an external monitor is plugged in, and it remains fixed even after an external monitor is unplugged. I may have to investigate further, but it doesn't appear to be wine after all.

**Comment by fmuelle4711** [comment]
Update: It appears to be wayland. The fix is to change the screen resolution to something, then start powerpnt, then change the screen resolution again to what you really want, and it works. Beats me, but the work-around works reliably (as does plugging in an external monitor).

**Comment by jahnf** [comment]
Thanks for the info, And that behavior is it only in conjunction with Wayland + wine/PowerPoint or a general issue with Projecteur + Wayland on your setup?

**Comment by fmuelle4711** [comment]
I can only confirm it w/ Wayland, wine+Powerpnt. It does not look like a projecteur issue. But it's not worth investigating since I'm using a legacy wine version (due to MS license issues), so I'm just reporting this in case someone else happens to look for a work-around. No need to change projecteur, IMHO.
