### ISSUE TITLE
Feature Request: Scroll on button hold

### ISSUE THREAD

**Issue by avsaase** [jahnf/Projecteur#85]
Hi, let me first thank you for making this software. I recently made the switch to Linux and not being able to use my Spotlight was one of the last things holding me back. So thanks for solving that issue!

One feature of the official software is that you can scroll by holding down a button (I don't remember which one, or if it is configurable) and rotating the presenter up and down to scroll. This allows you to quickly scroll through a lot of slides. I have no idea if this implementable with the new button mapping framework.

**Comment by jahnf** [comment]
> One feature of the official software is that you can scroll by holding down a button (I don't remember which one, or if it is configurable) and rotating the presenter up and down to scroll. This allows you to quickly scroll through a lot of slides. I have no idea if this implementable with the new button mapping framework.

Unfortunately no, it seems it's currently not possible. For that feature, most probably direct communication with the device is necessary (and reverse engineering what kind of messages the original Logitech software exchanges with the device) see also: #71 #6

**Comment by jahnf** [comment]
With the merge of PR #155 that contains a lot of work from @mayanksuman toward this feature - the latest alpha versions are now able to scroll with a configurable button press and hold (next or back).  (Logitech Spotlight)

Right click where you would record your button combination - then you can select the special inputs
_Next Hold_ and _Back Hold_ - with these inputs you can then choose from a different set of mapped actions.
![Screenshot from 2021-09-16 21-37-46](https://user-images.githubusercontent.com/5852240/133675464-27aaec10-7661-4ed8-8bdd-ecd1b5eb42d2.png)
