### ISSUE TITLE
i3 Window manager?: When opening preferences, the entire screen flickers

### ISSUE THREAD

**Issue by luca-ing** [jahnf/Projecteur#9]
**Observation:**
When I open Projecteur preferences,
* the entire screen flickers like mad (between, it seems, black and the actual screeen image).
* I can apparently only interact with the window while the screen isn't black. So I need to click everything many times, until I hit the right timing by luck (e.g. to close the window again)
* Once I close the window, the flickering stops

**Expectation:**
Opening the window should not produce any visual distortion, interaction with the window should be as usual

**Steps to reproduce:**
* Start Projecteur 0.4-alpha.9
* open the settings window
* always reproducible

**Environment:**
* compiled using qt 5.12.2
* using i3 window manager
* environment:
```bash
$ uname -a
Linux dell 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ i3 --version
i3 version 4.15 (2018-03-10) © 2009 Michael Stapelberg and contributors

```

**Comment by jahnf** [comment]
@luca-ing : Could you please retry with the lastest version from develop - especially with the preferences screen a lot changes since the version you reported the issue with. Thanks in advance.

**Comment by luca-ing** [comment]
In today's develop, I confirm the flickering is gone.

Thanks, @jahnf . I appreciate the work you put into this.
